### ISSUE TITLE
"Read timed out" when starting Firefox

### ISSUE THREAD

**Issue by maksr** [clj-commons/etaoin#356]
When I switched from Etaoin **0.3.6** to **0.4.1**, my

```
    (firefox :path-browser "..." :profile "...")
```

stopped working. It hanged for about 60 seconds and then wrote "Read timed out".

I found out it works if I don't use `:profile`, but I need this option (mostly because of trusted certificates missing by default in Firefox), so I included the two logging libraries

```
    [org.slf4j/slf4j-api "1.7.30"]
    [org.slf4j/slf4j-simple "1.7.30"]
```
and
```
    (System/setProperty org.slf4j.impl.SimpleLogger/DEFAULT_LOG_LEVEL_KEY "TRACE")
```
The difference between **0.3.6** and **0.4.1** is that the former starts the webdriver with  
```
geckodriver --port 4444 --marionette-port 2828  
```
while the later with  
```
geckodriver --port 61000 --log trace
```
I solved the problem by adding  
```
    :args-driver ["--marionette-port" "2828"]
```
to `(firefox...)` call and now works fine with `:profile` also.

I don't know what can be done about this in Etaoin but maybe at least some hint can be given in the start guide of Etaoin when an interface to external programs changes from one version to another. Or maybe now the users will find this post on their next "Read timed out".

Thank you however for a great and very useful library.

**Comment by zilti** [comment]
I found this bug report when looking if someone else has the Read Timed Out exception. For me it doesn't happen on startup, but the browser opens normally, and at some point during operation, it will just time out and fail. I suspect it happens when a webpage takes too long to load? But I am not sure.

**Comment by lread** [comment]
@maksr thanks for raising this issue.

So you stopped getting timeouts after you re-added `--marionette-port`?
I'd love to update the user guide with a tip, but I currently don't yet understand why you'd need this option for geckodriver. (Hey, I'm kinda new here! 🙂)

I realize it has been ages since you raised this issue, so I understand if you've moved on to other things. I will close this one if I don't hear any elaborations from anyone by June 30th, 2022.

**Comment by lread** [comment]
Ok, gonna close this one up. Please re-open if there is still an issue that needs addressing here.
